DELETE https://hidden-ravine-95959.herokuapp.com/api/persons/4

###
POST https://hidden-ravine-95959.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Mikke Blakley",
    "number": "24524354"
}